"""LLM-generated company list — supplementary search source alongside SerpAPI.

The LLM is asked to name real companies in the given niche/city.
Every URL it returns is HEAD-validated (3 s timeout) before entering
the expensive crawl pipeline, so hallucinated domains are dropped fast.
"""
from __future__ import annotations

import asyncio
import json
import logging

import httpx

from app.services.llm.base import LLMMessage
from app.services.llm.factory import get_llm_client
from app.services.llm.logged import LoggedLLMCall, logged_chat

logger = logging.getLogger(__name__)

_PROMPT = """\
Ты эксперт по B2B-рынку России.
Назови {count} реальных компаний из ниши "{niche}" в городе "{city}".
Только реальные компании с работающими сайтами — не выдумывай URL.

Отвечай строго JSON без markdown:
{{"companies":[{{"name":"...","website":"https://...","city":"...","description":"..."}}]}}"""


async def llm_search_companies(
    niche: str,
    city: str | None,
    count: int = 15,
    log: LoggedLLMCall | None = None,
) -> list[dict]:
    """Return HEAD-validated company list generated by the LLM."""
    client = get_llm_client("classify")
    prompt = _PROMPT.format(
        count=count,
        niche=niche,
        city=city or "России",
    )

    dummy_log = log or LoggedLLMCall()
    try:
        result = await logged_chat(
            client,
            [LLMMessage(role="user", content=prompt)],
            stage="llm_search",
            log=dummy_log,
            temperature=0.3,
            max_tokens=1024,
            timeout=30.0,
            response_format={"type": "json_object"},
        )
    except Exception as exc:
        logger.warning("llm_search: LLM call failed: %r", exc)
        return []

    text = (result.content or "").strip()
    if text.startswith("```"):
        text = text.split("```")[1].lstrip("json").strip()

    try:
        data = json.loads(text)
        companies = data.get("companies", [])
        if not isinstance(companies, list):
            return []
    except Exception:
        logger.warning("llm_search: failed to parse JSON: %r", text[:200])
        return []

    # Filter malformed entries
    candidates = [
        c for c in companies
        if isinstance(c, dict) and isinstance(c.get("website"), str) and c["website"].startswith("http")
    ]
    if not candidates:
        return []

    logger.info("llm_search: got %d candidates from LLM, HEAD-validating…", len(candidates))
    validated = await _head_validate(candidates)
    logger.info("llm_search: %d/%d passed HEAD validation", len(validated), len(candidates))
    return validated


async def _head_check(session: httpx.AsyncClient, company: dict) -> dict | None:
    url = company["website"].rstrip("/")
    try:
        resp = await session.head(url, timeout=3.0, follow_redirects=True)
        if resp.status_code < 400:
            return {**company, "source": "llm_search"}
    except Exception:
        pass
    return None


async def _head_validate(companies: list[dict]) -> list[dict]:
    async with httpx.AsyncClient(
        headers={"User-Agent": "Mozilla/5.0 (compatible; LeadBot/1.0)"},
        follow_redirects=True,
    ) as session:
        results = await asyncio.gather(
            *[_head_check(session, c) for c in companies],
            return_exceptions=True,
        )
    return [r for r in results if isinstance(r, dict)]
